version: "3.8"
services:
  db:
    container_name: "sql-query"
    image: rakimsth/sql-query
    restart: always
    env_file: "./.env"
    ports:
      - "3000:3000"
volumes:
  db:
    driver: local
